# Generated by Django 4.1.4 on 2022-12-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "father_name",
                    models.CharField(max_length=100, verbose_name="Primer apellido"),
                ),
                (
                    "mother_name",
                    models.CharField(max_length=100, verbose_name="Segundo apellido"),
                ),
                (
                    "job",
                    models.CharField(max_length=100, verbose_name="Puesto de trabajo"),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salario"
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="Estatus")),
                (
                    "contract_day",
                    models.DateTimeField(verbose_name="Fecha de contrato"),
                ),
                ("date_name", models.DateTimeField(verbose_name="Fecha de nacimiento")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "db_table": "empleado",
            },
        ),
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "father_name",
                    models.CharField(max_length=100, verbose_name="Primer apellido"),
                ),
                (
                    "mother_name",
                    models.CharField(max_length=100, verbose_name="Segundo apellido"),
                ),
                (
                    "partent",
                    models.CharField(max_length=100, verbose_name="Parentesco"),
                ),
                ("sex", models.CharField(max_length=20, verbose_name="Sexo")),
                ("date_name", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.empleado",
                        verbose_name="Empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiario",
                "verbose_name_plural": "Beneficiarios",
                "db_table": "beneficiario",
            },
        ),
    ]
